### ISSUE TITLE
Couldn't load plugin 'nnmlf' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by Navid61** [Marconi-Martins/NNMLF#1]
Hi,
I installed this plugin on QGIS 3.22 LTS I got this error

Couldn't load plugin 'nnmlf' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'resources_rc' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins/nnmlf/__init__.py", line 35, in classFactory
    from .NNMLF import NNMLF
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins/nnmlf/NNMLF.py", line 68, in 
    from nnmlf.JanelaAjuda import Ui_MainWindow
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/sigma/.local/share/QGIS/QGIS3/profiles/default/python/plugins/nnmlf/JanelaAjuda.py", line 78, in 
    import resources_rc
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'resources_rc'

Do you know how can I fix that? Although it installed finally, I've doubt it works without any problem.

**Comment by Marconi-Martins** [comment]
Hi, Navid

How many lines does your shape have?
If there are less than 4 there will be an error, due to the fact that the
plugin works until the third order. In the next update I will put a
condition for this not to happen. If you want, send me your shape and let
me know the size of the area, so I can check.
Thanks.

Em sex., 27 de jan. de 2023 às 02:43, Navid ***@***.***>
escreveu:

**Comment by Navid61** [comment]
Hi,
I got this error message during installation precedure, I did not add any shapefiles or any other file format.

**Comment by Marconi-Martins** [comment]
Hi, Navid

Try to install on version 3.16. Even this version is working.

Em sex., 27 de jan. de 2023 às 13:10, Navid ***@***.***>
escreveu:
